#!/usr/bin/env node
// Embeds the three mascot images from site/assets/ into the scanner, so the HTML report and the local web page can show
// Armo without any file next to them (the report is a single self-contained file and makes no network request).
//
//   node scripts/build-mascot.js          rewrite packages/scanner/src/output/mascot-data.ts
//   node scripts/build-mascot.js --check  exit 1 if that file is out of date (used by a test)
//
// To change the artwork: replace site/assets/mascot-{safe,warn,danger}.(svg|png|webp), then run `npm run mascot`.
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const assets = path.join(root, "site", "assets");
const target = path.join(root, "packages", "scanner", "src", "output", "mascot-data.ts");

const MOODS = { green: "safe", yellow: "warn", red: "danger" };
const MIME = { ".svg": "image/svg+xml", ".png": "image/png", ".webp": "image/webp" };
const MAX_BYTES = 150 * 1024; // each image is embedded in every report, so keep them small

function findImage(name) {
  for (const ext of Object.keys(MIME)) {
    const file = path.join(assets, `mascot-${name}${ext}`);
    if (fs.existsSync(file)) return { file, ext };
  }
  throw new Error(`site/assets/mascot-${name}.(svg|png|webp) is missing`);
}

function render() {
  const lines = [
    "// GENERATED by scripts/build-mascot.js from site/assets/mascot-*. Do not edit by hand: run `npm run mascot`.",
    "export const MASCOT_IMAGES: Record<\"green\" | \"yellow\" | \"red\", { mime: string; base64: string }> = {",
  ];
  for (const [color, name] of Object.entries(MOODS)) {
    const { file, ext } = findImage(name);
    const bytes = fs.readFileSync(file);
    if (bytes.length > MAX_BYTES) {
      throw new Error(`${path.relative(root, file)} is ${Math.round(bytes.length / 1024)} KB; keep each mascot under ${MAX_BYTES / 1024} KB`);
    }
    lines.push(`  ${color}: { mime: "${MIME[ext]}", base64: "${bytes.toString("base64")}" },`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

const output = render();
if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  if (current !== output) {
    console.error("mascot-data.ts is out of date: run `npm run mascot`");
    process.exit(1);
  }
} else {
  fs.writeFileSync(target, output);
  console.log(`wrote ${path.relative(root, target)}`);
}
